---
- hosts: all
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /app/keys/mewc-key
  become: yes
  tasks:
    - name: Create barry
      user:
        name: barry
        password: "$6$H6xJ/cGxiiFzhWFj$SP21sqmEBzVBjtYtJySO5EoBdt3uxnjkwftDJV8Leq1a/L3NI30wSLfghvmVp6s/aF5dcT7NxFbBjkIucXWh9/"
        shell: /bin/bash
        comment: "Guest User with regular shell"
        home: /mnt/mewc-volume/service

    - name: Ensure directory exists for user's home
      file:
        path: /mnt/mewc-volume/service
        state: directory
        owner: barry
        group: barry
        mode: '0755'

    - name: Ensure password authentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Restart sshd

    - name: Ensure challenge response authentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication yes'
        state: present
      notify: Restart sshd

    - name: Comment out Include directive
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '^(Include \/etc\/ssh\/sshd_config\.d\/\*\.conf)'
        replace: '#\1'
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: ssh
        state: restarted

