---
- hosts: all
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /app/keys/mewc-key
  become: yes
  tasks:
    - name: Ensure the directory for mounting exists
      file:
        path: /mnt/mewc-volume
        state: directory

    - name: Check if the volume has a filesystem
      command: file -s /dev/vdb
      register: volume_check
      changed_when: false

    - name: Format the volume with ext4
      filesystem:
        fstype: ext4
        dev: /dev/vdb
      when: "'/dev/vdb: data' in volume_check.stdout"

    - name: Mount the volume
      mount:
        path: /mnt/mewc-volume
        src: /dev/vdb
        fstype: ext4
        state: mounted

    # Stop Docker service
    - name: Stop Docker service
      systemd:
        name: docker
        state: stopped

    # Move the Docker data directory to the new volume
    - name: Move Docker's data directory to the new volume
      command: mv /var/lib/docker /mnt/mewc-volume/

    # Ensure Docker's new data directory exists (precautionary)
    - name: Ensure Docker's new data directory exists
      file:
        path: /mnt/mewc-volume/docker
        state: directory

    # Modify Docker's systemd service file
    - name: Point Docker to the new data directory
      lineinfile:
        path: /lib/systemd/system/docker.service
        regexp: '^ExecStart='
        line: 'ExecStart=/usr/bin/dockerd --data-root=/mnt/mewc-volume/docker -H fd://'
      register: docker_service_changed

    # Reload the systemd configuration
    - name: Reload systemd configuration
      command: systemctl daemon-reload
      when: docker_service_changed.changed

    # Start Docker
    - name: Start Docker service
      systemd:
        name: docker
        state: started
