---
- hosts: all
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /app/keys/mewc-key
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy stub index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!doctype html>
          <meta charset="utf-8">
          <title>MEWC Web — Stub</title>
          <style>
            body{font-family:system-ui;background:#0b0c10;color:#e5e7eb;display:grid;place-items:center;height:100vh;margin:0}
            .card{background:#111318;padding:24px;border-radius:16px;box-shadow:0 6px 24px rgba(0,0,0,.25);text-align:center}
            img{width:96px;height:96px;display:block;margin:0 auto 12px}
          </style>
          <div class="card">
            <img src="/mewc_logo_hex.png" alt="MEWC">
            <h1>MEWC web test is alive</h1>
            <p>CPU-only POC — nginx served via Ansible.</p>
          </div>

    - name: Copy logo
      copy:
        src: "{{ playbook_dir }}/mewc_logo_hex.png"
        dest: /var/www/html/mewc_logo_hex.png
        mode: "0644"

    - name: Ensure nginx running
      service:
        name: nginx
        state: started
        enabled: yes