---
- hosts: all
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /app/keys/mewc-key
  become: yes
  tasks:
  - name: Notify user about the next task
    debug:
      msg: "Pulling the Docker images will take a while, go enjoy a coffee..."
  - name: Pull required Docker images
    docker_image:
      name: "{{ item }}"
      source: pull
    loop:
      - zaandahl/mewc-detect:latest
      - zaandahl/mewc-snip:latest
      - zaandahl/mewc-box:latest
      - zaandahl/mewc-exif:latest
      - zaandahl/mewc-predict:latest
      - zaandahl/mewc-train:latest
      # Add other images as needed
